<?php
/**
 * @file
 * Module file for qtrServices.
 */

/**
 * Implements hook_services_resources().
 */
function qtrServices_services_resources() {
  module_load_include('inc', 'qtrServices', 'resources/report');
  module_load_include('inc', 'qtrServices', 'resources/translations');
  module_load_include('inc', 'qtrServices', 'resources/project');
  module_load_include('inc', 'qtrServices', 'resources/vocabulary');

  $resources['report'] = _qtrServices_report();
  $resources['translations'] = _qtrServices_translations();
  $resources['project'] = _qtrServices_project();
  $resources['vocabulary'] = _qtrServices_vocabulary();
  return $resources;
}

/**
 * Implements hook_boot().
 */
function qtrServices_boot() {
  if ($_SERVER['REQUEST_METHOD'] == "OPTIONS") {
    //header('Access-Control-Allow-Origin: ' . $_SERVER['HTTP_ORIGIN']);
    header('Access-Control-Allow-Origin: *');
    header('Access-Control-Allow-Methods: POST, GET');
    header('Access-Control-Allow-Headers: Authorization');
    header('Access-Control-Max-Age: 1728000');
    header("Content-Length: 0");
    header("Content-Type: text/plain");
    exit(0);
  }
}
